services:
  - type: worker
    name: telegram-lawbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_API_ID
        value: your_api_id
      - key: TELEGRAM_API_HASH
        value: your_api_hash
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token
      - key: OPENAI_API_KEY
        value: your_openai_key
